name: Build LaTeX document
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        texlive: [latest, 2024, 2023]
        # 多版本 TexLive 兼容性测试
        # 版本号选自：https://github.com/xu-cheng/latex-action?tab=readme-ov-file#environment-configuration
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Tree All project
        run: |
          apt update && apt install -y tree
          tree

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            main.tex
            main_english.tex
            slides.tex
          latexmk_use_xelatex: true
          texlive_version: ${{ matrix.texlive }}

      - name: Publish PDF as actions assets
        uses: actions/upload-artifact@v4
        with:
          name: Example-PDFs-texlive-${{ matrix.texlive }}
          path: |
            main.pdf
            main_english.pdf
            slides.pdf

      - name: look files
        run: |
          tree
